// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSXYontvRwDt27J257Uvsc6zh8FSEWHv8',
    appId: '1:762075119619:web:0787159ecd9f8fc313ce36',
    messagingSenderId: '762075119619',
    projectId: 'warta-30764',
    authDomain: 'warta-30764.firebaseapp.com',
    storageBucket: 'warta-30764.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3o_VoMHFLul_xg_lKEyjAXYp7yzYE9ks',
    appId: '1:762075119619:android:f0e4ccbc92591f5d13ce36',
    messagingSenderId: '762075119619',
    projectId: 'warta-30764',
    storageBucket: 'warta-30764.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAHjqTxJ8J3EhYJWr5h9Sw66kNjrsgW80',
    appId: '1:762075119619:ios:38b50c5aa1e55e2713ce36',
    messagingSenderId: '762075119619',
    projectId: 'warta-30764',
    storageBucket: 'warta-30764.appspot.com',
    androidClientId: '762075119619-tb8sbedsb5jo97sb4t4ojtt1mdpihqfd.apps.googleusercontent.com',
    iosClientId: '762075119619-16ita5qiposs1i30f5nvdmd82b8qgcv1.apps.googleusercontent.com',
    iosBundleId: 'com.example.warta',
  );
}
